const Map<String, String> enUS = {
  // General
  'app_name': 'The Ramp',
  'ok': 'OK',
  'cancel': 'Cancel',
  'retry': 'Retry',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'apply': 'Apply',
  'clear': 'Clear',
  'clear_all': 'Clear all',
  'done': 'Done',
  'see_all': 'See all',
  'loading': 'Loading…',
  'confirm': 'Confirm',
  'yes': 'Yes',
  'no': 'No',
  'off_label': 'OFF',
  'free': 'FREE',

  // Errors / empty states
  'error_generic': 'Something went wrong. Please try again.',
  'error_no_internet': 'No internet connection',
  'error_no_internet_desc': 'Check your connection and try again.',
  'error_auth': 'Authentication failed. Please try again.',
  'error_payment': 'Payment could not be completed.',
  'error_timeout': 'Request timed out. Please try again.',
  'error_field_required': 'This field is required',
  'error_phone_required': 'Please enter your mobile number',
  'error_phone_invalid': 'Enter a valid 10-digit mobile number',
  'error_name_short': 'Name is too short',
  'error_email_invalid': 'Enter a valid email address',
  'error_pincode_invalid': 'Enter a valid 6-digit PIN code',
  'error_otp_invalid': 'Incorrect OTP. Please try again.',
  'error_image_load': 'Image failed to load',
  'empty_generic': 'Nothing here yet',
  'offline_banner': 'You are offline. Some features may not work.',

  // Auth
  'login': 'Login',
  'login_required_generic': 'Log in to continue',
  'login_required_cart': 'Log in to view your cart',
  'login_required_wishlist': 'Log in to see your wishlist',
  'login_required_profile': 'Log in to access your profile',
  'login_title': 'Welcome to The Ramp',
  'login_subtitle': 'Fashion that fits you. Log in with your mobile number.',
  'phone_number': 'Mobile number',
  'send_otp': 'Send OTP',
  'otp_title': 'Verify your number',
  'otp_subtitle': 'Enter the 6-digit code sent to @phone',
  'verify': 'Verify',
  'resend_otp': 'Resend OTP',
  'resend_in': 'Resend in @secondss',
  'otp_sent': 'OTP sent successfully',
  'logout': 'Log out',
  'logout_confirm': 'Are you sure you want to log out?',

  // Navigation
  'nav_home': 'Home',
  'nav_categories': 'Categories',
  'nav_cart': 'Cart',
  'nav_wishlist': 'Wishlist',
  'nav_profile': 'Profile',

  // Home
  'search_hint': 'Search for shirts, dresses, shoes…',
  'flash_sale': 'Flash Sale',
  'ends_in': 'Ends in',
  'new_arrivals': 'New Arrivals',
  'best_sellers': 'Best Sellers',
  'recommended': 'Recommended For You',
  'recently_viewed': 'Recently Viewed',
  'continue_shopping': 'Continue Shopping',
  'top_deals': 'Top Deals',
  'featured_categories': 'Shop by Category',

  // Categories
  'categories_title': 'Categories',
  'cat_men': 'Men',
  'cat_women': 'Women',
  'cat_kids': 'Kids',
  'cat_footwear': 'Footwear',
  'cat_accessories': 'Accessories',

  // Product listing
  'filters': 'Filters',
  'sort_by': 'Sort by',
  'sort_newest': 'Newest',
  'sort_popularity': 'Popularity',
  'sort_rating': 'Rating',
  'sort_price_low_high': 'Price: Low to High',
  'sort_price_high_low': 'Price: High to Low',
  'filter_price': 'Price',
  'filter_brand': 'Brand',
  'filter_color': 'Color',
  'filter_size': 'Size',
  'filter_discount': 'Discount',
  'filter_availability': 'Availability',
  'in_stock_only': 'In stock only',
  'discount_10_plus': '10% or more',
  'discount_25_plus': '25% or more',
  'discount_50_plus': '50% or more',
  'no_products_found': 'No products found',
  'no_products_found_desc': 'Try changing your filters or search term.',
  'products_count': '@count products',

  // Product details
  'product_details': 'Product Details',
  'select_size': 'Select Size',
  'select_color': 'Select Color',
  'in_stock': 'In stock',
  'out_of_stock': 'Out of stock',
  'only_left': 'Only @count left!',
  'description': 'Description',
  'specifications': 'Specifications',
  'reviews': 'Reviews',
  'ratings_reviews': 'Ratings & Reviews',
  'related_products': 'Related Products',
  'similar_products': 'Similar Products',
  'add_to_cart': 'Add to Cart',
  'go_to_cart': 'Go to Cart',
  'buy_now': 'Buy Now',
  'estimated_delivery': 'Estimated delivery by @date',
  'available_offers': 'Available Offers',
  'share_product_text': 'Check out @name on The Ramp!',
  'select_size_first': 'Please select a size',
  'select_color_first': 'Please select a color',
  'added_to_cart': 'Added to cart',
  'added_to_wishlist': 'Added to wishlist',
  'removed_from_wishlist': 'Removed from wishlist',

  // Wishlist
  'wishlist_title': 'My Wishlist',
  'wishlist_empty': 'Your wishlist is empty',
  'wishlist_empty_desc': 'Tap the heart on any product to save it here.',
  'move_to_cart': 'Move to Cart',

  // Cart
  'cart_title': 'My Cart',
  'cart_empty': 'Your cart is empty',
  'cart_empty_desc': 'Browse products and add them to your cart.',
  'start_shopping': 'Start Shopping',
  'save_for_later': 'Save for later',
  'saved_for_later': 'Saved for later',
  'move_back_to_cart': 'Move to cart',
  'remove': 'Remove',
  'coupon_code': 'Coupon code',
  'apply_coupon': 'Apply',
  'coupon_applied': 'Coupon applied!',
  'coupon_invalid': 'Invalid or expired coupon',
  'coupon_min_order': 'Minimum order value for this coupon is @amount',
  'price_details': 'Price Details',
  'subtotal': 'Subtotal',
  'discount': 'Discount',
  'coupon_discount': 'Coupon discount',
  'delivery_charges': 'Delivery charges',
  'taxes': 'Taxes',
  'total_amount': 'Total Amount',
  'free_shipping_msg': 'Add @amount more for FREE delivery',
  'proceed_to_checkout': 'Proceed to Checkout',
  'quantity': 'Qty',

  // Checkout
  'checkout_title': 'Checkout',
  'delivery_address': 'Delivery Address',
  'add_address': 'Add Address',
  'add_new_address': 'Add New Address',
  'edit_address': 'Edit Address',
  'delete_address_confirm': 'Delete this address?',
  'no_addresses': 'No saved addresses',
  'no_addresses_desc': 'Add a delivery address to continue.',
  'full_name': 'Full name',
  'address_line1': 'House no., building, street',
  'address_line2': 'Area, locality (optional)',
  'city': 'City',
  'state': 'State',
  'pincode': 'PIN code',
  'address_type': 'Address type',
  'address_home': 'Home',
  'address_work': 'Work',
  'address_other': 'Other',
  'default_address': 'Default address',
  'delivery_options': 'Delivery Options',
  'delivery_standard': 'Standard delivery',
  'delivery_standard_desc': '3–7 business days',
  'delivery_express': 'Express delivery',
  'delivery_express_desc': '1–2 business days (+₹99)',
  'payment_method': 'Payment Method',
  'pay_razorpay': 'Card / Netbanking / Wallet',
  'pay_upi': 'UPI',
  'pay_cod': 'Cash on Delivery',
  'order_review': 'Order Review',
  'place_order': 'Place Order',
  'pay_now': 'Pay @amount',
  'order_success': 'Order placed successfully!',
  'order_success_desc': 'Thank you for shopping with us. Track your order in My Orders.',
  'view_order': 'View Order',
  'payment_failed_title': 'Payment failed',
  'payment_failed_desc': 'Your payment could not be processed. No money was deducted, or it will be refunded.',
  'retry_payment': 'Retry Payment',
  'payment_cancelled': 'Payment cancelled',

  // Orders
  'my_orders': 'My Orders',
  'orders_empty': 'No orders yet',
  'orders_empty_desc': 'Your orders will appear here after you shop.',
  'order_id': 'Order ID',
  'order_status_pending': 'Pending',
  'order_status_confirmed': 'Confirmed',
  'order_status_shipped': 'Shipped',
  'order_status_out_for_delivery': 'Out for delivery',
  'order_status_delivered': 'Delivered',
  'order_status_cancelled': 'Cancelled',
  'order_status_returned': 'Returned',
  'order_status_return_requested': 'Return requested',
  'tab_current': 'Current',
  'tab_completed': 'Completed',
  'tab_cancelled': 'Cancelled',
  'tab_returned': 'Returned',
  'order_details': 'Order Details',
  'order_tracking': 'Order Tracking',
  'cancel_order': 'Cancel Order',
  'cancel_order_confirm': 'Are you sure you want to cancel this order?',
  'order_cancelled_msg': 'Order cancelled',
  'return_order': 'Request Return',
  'return_reason': 'Reason for return',
  'return_requested_msg': 'Return requested',
  'invoice': 'Invoice',
  'reorder': 'Reorder',
  'items_count': '@count items',
  'ordered_on': 'Ordered on @date',
  'paid_via': 'Paid via @method',
  'shipping_address': 'Shipping address',

  // Profile
  'profile_title': 'My Profile',
  'edit_profile': 'Edit Profile',
  'display_name': 'Name',
  'email': 'Email (optional)',
  'profile_updated': 'Profile updated',
  'saved_addresses': 'Saved Addresses',
  'saved_payments': 'Saved Payment Methods',
  'notifications_title': 'Notifications',
  'notifications_empty': 'No notifications yet',
  'language': 'Language',
  'select_language': 'Select Language',
  'theme': 'Theme',
  'theme_system': 'System default',
  'theme_light': 'Light',
  'theme_dark': 'Dark',
  'guest': 'Guest',

  // Search
  'search_title': 'Search',
  'recent_searches': 'Recent Searches',
  'trending_searches': 'Trending Searches',
  'no_results_for': 'No results for "@query"',
  'voice_search_coming_soon': 'Voice search is coming soon',

  // Reviews
  'write_review': 'Write a Review',
  'your_rating': 'Your rating',
  'review_hint': 'Share your experience with this product…',
  'add_photos': 'Add photos',
  'submit_review': 'Submit Review',
  'review_submitted': 'Thank you! Your review has been submitted.',
  'helpful': 'Helpful',
  'no_reviews': 'No reviews yet. Be the first to review!',
  'based_on_reviews': 'Based on @count reviews',
  'login_to_review': 'Log in to write a review',

  // Admin panel
  'admin_panel': 'Admin Panel',
  'admin_products': 'Products',
  'admin_categories': 'Categories',
  'admin_banners': 'Banners',
  'admin_coupons': 'Coupons',
  'add_product': 'Add Product',
  'edit_product': 'Edit Product',
  'add_category': 'Add Category',
  'edit_category': 'Edit Category',
  'add_subcategory': 'Add Subcategory',
  'add_banner': 'Add Banner',
  'edit_banner': 'Edit Banner',
  'add_coupon': 'Add Coupon',
  'edit_coupon': 'Edit Coupon',
  'field_name': 'Name',
  'field_brand': 'Brand',
  'field_category': 'Category',
  'field_subcategory': 'Subcategory (optional)',
  'field_mrp': 'MRP (₹)',
  'field_price': 'Selling price (₹)',
  'field_stock': 'Stock quantity',
  'field_colors': 'Colors (comma separated)',
  'field_sizes': 'Sizes (comma separated)',
  'field_images': 'Image URLs (one per line)',
  'field_keywords': 'Search keywords (comma separated)',
  'field_description': 'Description',
  'field_specs': 'Specifications (key: value per line)',
  'field_offers': 'Offers (one per line)',
  'field_sort_order': 'Sort order',
  'field_image_url': 'Image URL',
  'field_title': 'Title',
  'field_active': 'Active',
  'flag_featured': 'Featured (Recommended)',
  'flag_bestseller': 'Best Seller',
  'flag_flash_sale': 'Flash Sale',
  'flash_sale_hours': 'Flash sale duration (hours from now)',
  'field_target': 'Tap target',
  'target_none': 'None',
  'target_category': 'Category',
  'target_product': 'Product',
  'field_target_id': 'Target ID (category/product)',
  'field_coupon_code': 'Coupon code',
  'field_coupon_type': 'Type',
  'coupon_percent': 'Percent off',
  'coupon_flat': 'Flat amount off',
  'field_coupon_value': 'Value (% or ₹)',
  'field_min_order': 'Minimum order (₹)',
  'field_max_discount': 'Max discount (₹, 0 = none)',
  'field_expiry_days': 'Expires in (days, 0 = never)',
  'saved_success': 'Saved',
  'deleted_success': 'Deleted',
  'delete_confirm_generic': 'Delete this item? This cannot be undone.',
  'no_items_yet': 'Nothing here yet. Tap + to add.',
  'admin_subtitle': 'Manage store content',
};
