const Map<String, String> hiIN = {
  // General
  'app_name': 'The Ramp',
  'ok': 'ठीक है',
  'cancel': 'रद्द करें',
  'retry': 'पुनः प्रयास करें',
  'save': 'सहेजें',
  'delete': 'हटाएं',
  'edit': 'बदलें',
  'apply': 'लागू करें',
  'clear': 'साफ़ करें',
  'clear_all': 'सभी साफ़ करें',
  'done': 'हो गया',
  'see_all': 'सभी देखें',
  'loading': 'लोड हो रहा है…',
  'confirm': 'पुष्टि करें',
  'yes': 'हाँ',
  'no': 'नहीं',
  'off_label': 'छूट',
  'free': 'मुफ़्त',

  // Errors / empty states
  'error_generic': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',
  'error_no_internet': 'इंटरनेट कनेक्शन नहीं है',
  'error_no_internet_desc': 'अपना कनेक्शन जांचें और पुनः प्रयास करें।',
  'error_auth': 'प्रमाणीकरण विफल रहा। कृपया पुनः प्रयास करें।',
  'error_payment': 'भुगतान पूरा नहीं हो सका।',
  'error_timeout': 'अनुरोध का समय समाप्त हो गया। पुनः प्रयास करें।',
  'error_field_required': 'यह फ़ील्ड आवश्यक है',
  'error_phone_required': 'कृपया अपना मोबाइल नंबर दर्ज करें',
  'error_phone_invalid': 'मान्य 10 अंकों का मोबाइल नंबर दर्ज करें',
  'error_name_short': 'नाम बहुत छोटा है',
  'error_email_invalid': 'मान्य ईमेल पता दर्ज करें',
  'error_pincode_invalid': 'मान्य 6 अंकों का पिन कोड दर्ज करें',
  'error_otp_invalid': 'गलत OTP। कृपया पुनः प्रयास करें।',
  'error_image_load': 'छवि लोड नहीं हो सकी',
  'empty_generic': 'अभी यहाँ कुछ नहीं है',
  'offline_banner': 'आप ऑफ़लाइन हैं। कुछ सुविधाएँ काम नहीं कर सकतीं।',

  // Auth
  'login': 'लॉग इन',
  'login_required_generic': 'जारी रखने के लिए लॉग इन करें',
  'login_required_cart': 'अपना कार्ट देखने के लिए लॉग इन करें',
  'login_required_wishlist': 'अपनी विशलिस्ट देखने के लिए लॉग इन करें',
  'login_required_profile': 'अपनी प्रोफ़ाइल के लिए लॉग इन करें',
  'login_title': 'The Ramp में आपका स्वागत है',
  'login_subtitle': 'फैशन जो आप पर जँचे। अपने मोबाइल नंबर से लॉग इन करें।',
  'phone_number': 'मोबाइल नंबर',
  'send_otp': 'OTP भेजें',
  'otp_title': 'अपना नंबर सत्यापित करें',
  'otp_subtitle': '@phone पर भेजा गया 6 अंकों का कोड दर्ज करें',
  'verify': 'सत्यापित करें',
  'resend_otp': 'OTP पुनः भेजें',
  'resend_in': '@seconds सेकंड में पुनः भेजें',
  'otp_sent': 'OTP सफलतापूर्वक भेजा गया',
  'logout': 'लॉग आउट',
  'logout_confirm': 'क्या आप लॉग आउट करना चाहते हैं?',

  // Navigation
  'nav_home': 'होम',
  'nav_categories': 'श्रेणियाँ',
  'nav_cart': 'कार्ट',
  'nav_wishlist': 'विशलिस्ट',
  'nav_profile': 'प्रोफ़ाइल',

  // Home
  'search_hint': 'शर्ट, ड्रेस, जूते खोजें…',
  'flash_sale': 'फ्लैश सेल',
  'ends_in': 'समाप्ति में',
  'new_arrivals': 'नए उत्पाद',
  'best_sellers': 'बेस्ट सेलर',
  'recommended': 'आपके लिए अनुशंसित',
  'recently_viewed': 'हाल ही में देखे गए',
  'continue_shopping': 'खरीदारी जारी रखें',
  'top_deals': 'बेहतरीन डील',
  'featured_categories': 'श्रेणी के अनुसार खरीदें',

  // Categories
  'categories_title': 'श्रेणियाँ',
  'cat_men': 'पुरुष',
  'cat_women': 'महिलाएं',
  'cat_kids': 'बच्चे',
  'cat_footwear': 'फुटवियर',
  'cat_accessories': 'एक्सेसरीज़',

  // Product listing
  'filters': 'फ़िल्टर',
  'sort_by': 'क्रमबद्ध करें',
  'sort_newest': 'नवीनतम',
  'sort_popularity': 'लोकप्रियता',
  'sort_rating': 'रेटिंग',
  'sort_price_low_high': 'कीमत: कम से अधिक',
  'sort_price_high_low': 'कीमत: अधिक से कम',
  'filter_price': 'कीमत',
  'filter_brand': 'ब्रांड',
  'filter_color': 'रंग',
  'filter_size': 'साइज़',
  'filter_discount': 'छूट',
  'filter_availability': 'उपलब्धता',
  'in_stock_only': 'केवल स्टॉक में',
  'discount_10_plus': '10% या अधिक',
  'discount_25_plus': '25% या अधिक',
  'discount_50_plus': '50% या अधिक',
  'no_products_found': 'कोई उत्पाद नहीं मिला',
  'no_products_found_desc': 'फ़िल्टर या खोज शब्द बदलकर देखें।',
  'products_count': '@count उत्पाद',

  // Product details
  'product_details': 'उत्पाद विवरण',
  'select_size': 'साइज़ चुनें',
  'select_color': 'रंग चुनें',
  'in_stock': 'स्टॉक में',
  'out_of_stock': 'स्टॉक में नहीं',
  'only_left': 'केवल @count बचे!',
  'description': 'विवरण',
  'specifications': 'विशेषताएँ',
  'reviews': 'समीक्षाएँ',
  'ratings_reviews': 'रेटिंग और समीक्षाएँ',
  'related_products': 'संबंधित उत्पाद',
  'similar_products': 'मिलते-जुलते उत्पाद',
  'add_to_cart': 'कार्ट में जोड़ें',
  'go_to_cart': 'कार्ट देखें',
  'buy_now': 'अभी खरीदें',
  'estimated_delivery': '@date तक अनुमानित डिलीवरी',
  'available_offers': 'उपलब्ध ऑफ़र',
  'share_product_text': 'The Ramp पर @name देखें!',
  'select_size_first': 'कृपया साइज़ चुनें',
  'select_color_first': 'कृपया रंग चुनें',
  'added_to_cart': 'कार्ट में जोड़ा गया',
  'added_to_wishlist': 'विशलिस्ट में जोड़ा गया',
  'removed_from_wishlist': 'विशलिस्ट से हटाया गया',

  // Wishlist
  'wishlist_title': 'मेरी विशलिस्ट',
  'wishlist_empty': 'आपकी विशलिस्ट खाली है',
  'wishlist_empty_desc': 'किसी भी उत्पाद पर हार्ट दबाकर उसे यहाँ सहेजें।',
  'move_to_cart': 'कार्ट में ले जाएँ',

  // Cart
  'cart_title': 'मेरा कार्ट',
  'cart_empty': 'आपका कार्ट खाली है',
  'cart_empty_desc': 'उत्पाद ब्राउज़ करें और कार्ट में जोड़ें।',
  'start_shopping': 'खरीदारी शुरू करें',
  'save_for_later': 'बाद के लिए सहेजें',
  'saved_for_later': 'बाद के लिए सहेजे गए',
  'move_back_to_cart': 'कार्ट में ले जाएँ',
  'remove': 'हटाएँ',
  'coupon_code': 'कूपन कोड',
  'apply_coupon': 'लागू करें',
  'coupon_applied': 'कूपन लागू हो गया!',
  'coupon_invalid': 'अमान्य या समाप्त कूपन',
  'coupon_min_order': 'इस कूपन के लिए न्यूनतम ऑर्डर @amount है',
  'price_details': 'मूल्य विवरण',
  'subtotal': 'उप-योग',
  'discount': 'छूट',
  'coupon_discount': 'कूपन छूट',
  'delivery_charges': 'डिलीवरी शुल्क',
  'taxes': 'कर',
  'total_amount': 'कुल राशि',
  'free_shipping_msg': 'मुफ़्त डिलीवरी के लिए @amount और जोड़ें',
  'proceed_to_checkout': 'चेकआउट करें',
  'quantity': 'मात्रा',

  // Checkout
  'checkout_title': 'चेकआउट',
  'delivery_address': 'डिलीवरी पता',
  'add_address': 'पता जोड़ें',
  'add_new_address': 'नया पता जोड़ें',
  'edit_address': 'पता बदलें',
  'delete_address_confirm': 'यह पता हटाएँ?',
  'no_addresses': 'कोई सहेजा गया पता नहीं',
  'no_addresses_desc': 'जारी रखने के लिए डिलीवरी पता जोड़ें।',
  'full_name': 'पूरा नाम',
  'address_line1': 'मकान नं., भवन, गली',
  'address_line2': 'क्षेत्र, इलाका (वैकल्पिक)',
  'city': 'शहर',
  'state': 'राज्य',
  'pincode': 'पिन कोड',
  'address_type': 'पते का प्रकार',
  'address_home': 'घर',
  'address_work': 'कार्यालय',
  'address_other': 'अन्य',
  'default_address': 'डिफ़ॉल्ट पता',
  'delivery_options': 'डिलीवरी विकल्प',
  'delivery_standard': 'मानक डिलीवरी',
  'delivery_standard_desc': '3–7 कार्य दिवस',
  'delivery_express': 'एक्सप्रेस डिलीवरी',
  'delivery_express_desc': '1–2 कार्य दिवस (+₹99)',
  'payment_method': 'भुगतान विधि',
  'pay_razorpay': 'कार्ड / नेटबैंकिंग / वॉलेट',
  'pay_upi': 'UPI',
  'pay_cod': 'कैश ऑन डिलीवरी',
  'order_review': 'ऑर्डर समीक्षा',
  'place_order': 'ऑर्डर करें',
  'pay_now': '@amount भुगतान करें',
  'order_success': 'ऑर्डर सफलतापूर्वक हो गया!',
  'order_success_desc': 'खरीदारी के लिए धन्यवाद। मेरे ऑर्डर में ट्रैक करें।',
  'view_order': 'ऑर्डर देखें',
  'payment_failed_title': 'भुगतान विफल',
  'payment_failed_desc': 'आपका भुगतान संसाधित नहीं हो सका। पैसा नहीं कटा है, या वापस कर दिया जाएगा।',
  'retry_payment': 'भुगतान पुनः करें',
  'payment_cancelled': 'भुगतान रद्द किया गया',

  // Orders
  'my_orders': 'मेरे ऑर्डर',
  'orders_empty': 'अभी कोई ऑर्डर नहीं',
  'orders_empty_desc': 'खरीदारी के बाद आपके ऑर्डर यहाँ दिखेंगे।',
  'order_id': 'ऑर्डर आईडी',
  'order_status_pending': 'लंबित',
  'order_status_confirmed': 'पुष्टि हुई',
  'order_status_shipped': 'भेजा गया',
  'order_status_out_for_delivery': 'डिलीवरी के लिए निकला',
  'order_status_delivered': 'डिलीवर हो गया',
  'order_status_cancelled': 'रद्द किया गया',
  'order_status_returned': 'वापस किया गया',
  'order_status_return_requested': 'वापसी का अनुरोध',
  'tab_current': 'वर्तमान',
  'tab_completed': 'पूर्ण',
  'tab_cancelled': 'रद्द',
  'tab_returned': 'वापसी',
  'order_details': 'ऑर्डर विवरण',
  'order_tracking': 'ऑर्डर ट्रैकिंग',
  'cancel_order': 'ऑर्डर रद्द करें',
  'cancel_order_confirm': 'क्या आप यह ऑर्डर रद्द करना चाहते हैं?',
  'order_cancelled_msg': 'ऑर्डर रद्द किया गया',
  'return_order': 'वापसी का अनुरोध करें',
  'return_reason': 'वापसी का कारण',
  'return_requested_msg': 'वापसी का अनुरोध किया गया',
  'invoice': 'चालान',
  'reorder': 'फिर से ऑर्डर करें',
  'items_count': '@count वस्तुएँ',
  'ordered_on': '@date को ऑर्डर किया',
  'paid_via': '@method से भुगतान',
  'shipping_address': 'शिपिंग पता',

  // Profile
  'profile_title': 'मेरी प्रोफ़ाइल',
  'edit_profile': 'प्रोफ़ाइल बदलें',
  'display_name': 'नाम',
  'email': 'ईमेल (वैकल्पिक)',
  'profile_updated': 'प्रोफ़ाइल अपडेट हो गई',
  'saved_addresses': 'सहेजे गए पते',
  'saved_payments': 'सहेजी गई भुगतान विधियाँ',
  'notifications_title': 'सूचनाएँ',
  'notifications_empty': 'अभी कोई सूचना नहीं',
  'language': 'भाषा',
  'select_language': 'भाषा चुनें',
  'theme': 'थीम',
  'theme_system': 'सिस्टम डिफ़ॉल्ट',
  'theme_light': 'लाइट',
  'theme_dark': 'डार्क',
  'guest': 'अतिथि',

  // Search
  'search_title': 'खोजें',
  'recent_searches': 'हाल की खोजें',
  'trending_searches': 'ट्रेंडिंग खोजें',
  'no_results_for': '"@query" के लिए कोई परिणाम नहीं',
  'voice_search_coming_soon': 'वॉइस खोज जल्द आ रही है',

  // Reviews
  'write_review': 'समीक्षा लिखें',
  'your_rating': 'आपकी रेटिंग',
  'review_hint': 'इस उत्पाद के साथ अपना अनुभव साझा करें…',
  'add_photos': 'फ़ोटो जोड़ें',
  'submit_review': 'समीक्षा सबमिट करें',
  'review_submitted': 'धन्यवाद! आपकी समीक्षा सबमिट हो गई।',
  'helpful': 'सहायक',
  'no_reviews': 'अभी कोई समीक्षा नहीं। पहली समीक्षा आप लिखें!',
  'based_on_reviews': '@count समीक्षाओं के आधार पर',
  'login_to_review': 'समीक्षा लिखने के लिए लॉग इन करें',

  // Admin panel
  'admin_panel': 'एडमिन पैनल',
  'admin_products': 'उत्पाद',
  'admin_categories': 'श्रेणियाँ',
  'admin_banners': 'बैनर',
  'admin_coupons': 'कूपन',
  'add_product': 'उत्पाद जोड़ें',
  'edit_product': 'उत्पाद बदलें',
  'add_category': 'श्रेणी जोड़ें',
  'edit_category': 'श्रेणी बदलें',
  'add_subcategory': 'उपश्रेणी जोड़ें',
  'add_banner': 'बैनर जोड़ें',
  'edit_banner': 'बैनर बदलें',
  'add_coupon': 'कूपन जोड़ें',
  'edit_coupon': 'कूपन बदलें',
  'field_name': 'नाम',
  'field_brand': 'ब्रांड',
  'field_category': 'श्रेणी',
  'field_subcategory': 'उपश्रेणी (वैकल्पिक)',
  'field_mrp': 'MRP (₹)',
  'field_price': 'बिक्री मूल्य (₹)',
  'field_stock': 'स्टॉक मात्रा',
  'field_colors': 'रंग (अल्पविराम से अलग)',
  'field_sizes': 'साइज़ (अल्पविराम से अलग)',
  'field_images': 'छवि URL (प्रति पंक्ति एक)',
  'field_keywords': 'खोज कीवर्ड (अल्पविराम से अलग)',
  'field_description': 'विवरण',
  'field_specs': 'विशेषताएँ (प्रति पंक्ति key: value)',
  'field_offers': 'ऑफ़र (प्रति पंक्ति एक)',
  'field_sort_order': 'क्रम संख्या',
  'field_image_url': 'छवि URL',
  'field_title': 'शीर्षक',
  'field_active': 'सक्रिय',
  'flag_featured': 'फ़ीचर्ड (अनुशंसित)',
  'flag_bestseller': 'बेस्ट सेलर',
  'flag_flash_sale': 'फ्लैश सेल',
  'flash_sale_hours': 'फ्लैश सेल अवधि (अभी से घंटे)',
  'field_target': 'टैप लक्ष्य',
  'target_none': 'कोई नहीं',
  'target_category': 'श्रेणी',
  'target_product': 'उत्पाद',
  'field_target_id': 'लक्ष्य ID (श्रेणी/उत्पाद)',
  'field_coupon_code': 'कूपन कोड',
  'field_coupon_type': 'प्रकार',
  'coupon_percent': 'प्रतिशत छूट',
  'coupon_flat': 'फ्लैट राशि छूट',
  'field_coupon_value': 'मान (% या ₹)',
  'field_min_order': 'न्यूनतम ऑर्डर (₹)',
  'field_max_discount': 'अधिकतम छूट (₹, 0 = कोई नहीं)',
  'field_expiry_days': 'समाप्ति (दिन, 0 = कभी नहीं)',
  'saved_success': 'सहेजा गया',
  'deleted_success': 'हटाया गया',
  'delete_confirm_generic': 'यह आइटम हटाएँ? इसे पूर्ववत नहीं किया जा सकता।',
  'no_items_yet': 'अभी यहाँ कुछ नहीं। जोड़ने के लिए + दबाएँ।',
  'admin_subtitle': 'स्टोर सामग्री प्रबंधित करें',
};
