const Map<String, String> mrIN = {
  // General
  'app_name': 'The Ramp',
  'ok': 'ठीक आहे',
  'cancel': 'रद्द करा',
  'retry': 'पुन्हा प्रयत्न करा',
  'save': 'जतन करा',
  'delete': 'हटवा',
  'edit': 'बदला',
  'apply': 'लागू करा',
  'clear': 'साफ करा',
  'clear_all': 'सर्व साफ करा',
  'done': 'झाले',
  'see_all': 'सर्व पहा',
  'loading': 'लोड होत आहे…',
  'confirm': 'पुष्टी करा',
  'yes': 'होय',
  'no': 'नाही',
  'off_label': 'सूट',
  'free': 'मोफत',

  // Errors / empty states
  'error_generic': 'काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.',
  'error_no_internet': 'इंटरनेट कनेक्शन नाही',
  'error_no_internet_desc': 'तुमचे कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.',
  'error_auth': 'प्रमाणीकरण अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
  'error_payment': 'पेमेंट पूर्ण होऊ शकले नाही.',
  'error_timeout': 'विनंतीची वेळ संपली. पुन्हा प्रयत्न करा.',
  'error_field_required': 'हे फील्ड आवश्यक आहे',
  'error_phone_required': 'कृपया तुमचा मोबाइल नंबर टाका',
  'error_phone_invalid': 'वैध 10 अंकी मोबाइल नंबर टाका',
  'error_name_short': 'नाव खूप लहान आहे',
  'error_email_invalid': 'वैध ईमेल पत्ता टाका',
  'error_pincode_invalid': 'वैध 6 अंकी पिन कोड टाका',
  'error_otp_invalid': 'चुकीचा OTP. कृपया पुन्हा प्रयत्न करा.',
  'error_image_load': 'प्रतिमा लोड होऊ शकली नाही',
  'empty_generic': 'इथे अजून काही नाही',
  'offline_banner': 'तुम्ही ऑफलाइन आहात. काही वैशिष्ट्ये कार्य करू शकत नाहीत.',

  // Auth
  'login': 'लॉग इन',
  'login_required_generic': 'पुढे जाण्यासाठी लॉग इन करा',
  'login_required_cart': 'तुमचे कार्ट पाहण्यासाठी लॉग इन करा',
  'login_required_wishlist': 'तुमची विशलिस्ट पाहण्यासाठी लॉग इन करा',
  'login_required_profile': 'तुमच्या प्रोफाइलसाठी लॉग इन करा',
  'login_title': 'The Ramp मध्ये आपले स्वागत आहे',
  'login_subtitle': 'तुम्हाला शोभेल असे फॅशन. तुमच्या मोबाइल नंबरने लॉग इन करा.',
  'phone_number': 'मोबाइल नंबर',
  'send_otp': 'OTP पाठवा',
  'otp_title': 'तुमचा नंबर सत्यापित करा',
  'otp_subtitle': '@phone वर पाठवलेला 6 अंकी कोड टाका',
  'verify': 'सत्यापित करा',
  'resend_otp': 'OTP पुन्हा पाठवा',
  'resend_in': '@seconds सेकंदात पुन्हा पाठवा',
  'otp_sent': 'OTP यशस्वीरित्या पाठवला',
  'logout': 'लॉग आउट',
  'logout_confirm': 'तुम्हाला नक्की लॉग आउट करायचे आहे का?',

  // Navigation
  'nav_home': 'होम',
  'nav_categories': 'श्रेणी',
  'nav_cart': 'कार्ट',
  'nav_wishlist': 'विशलिस्ट',
  'nav_profile': 'प्रोफाइल',

  // Home
  'search_hint': 'शर्ट, ड्रेस, बूट शोधा…',
  'flash_sale': 'फ्लॅश सेल',
  'ends_in': 'संपण्यास',
  'new_arrivals': 'नवीन उत्पादने',
  'best_sellers': 'बेस्ट सेलर',
  'recommended': 'तुमच्यासाठी शिफारस केलेले',
  'recently_viewed': 'अलीकडे पाहिलेले',
  'continue_shopping': 'खरेदी सुरू ठेवा',
  'top_deals': 'सर्वोत्तम डील',
  'featured_categories': 'श्रेणीनुसार खरेदी करा',

  // Categories
  'categories_title': 'श्रेणी',
  'cat_men': 'पुरुष',
  'cat_women': 'महिला',
  'cat_kids': 'मुले',
  'cat_footwear': 'पादत्राणे',
  'cat_accessories': 'अ‍ॅक्सेसरीज',

  // Product listing
  'filters': 'फिल्टर',
  'sort_by': 'क्रमवारी लावा',
  'sort_newest': 'नवीनतम',
  'sort_popularity': 'लोकप्रियता',
  'sort_rating': 'रेटिंग',
  'sort_price_low_high': 'किंमत: कमी ते जास्त',
  'sort_price_high_low': 'किंमत: जास्त ते कमी',
  'filter_price': 'किंमत',
  'filter_brand': 'ब्रँड',
  'filter_color': 'रंग',
  'filter_size': 'आकार',
  'filter_discount': 'सूट',
  'filter_availability': 'उपलब्धता',
  'in_stock_only': 'फक्त स्टॉकमधील',
  'discount_10_plus': '10% किंवा अधिक',
  'discount_25_plus': '25% किंवा अधिक',
  'discount_50_plus': '50% किंवा अधिक',
  'no_products_found': 'कोणतीही उत्पादने आढळली नाहीत',
  'no_products_found_desc': 'फिल्टर किंवा शोध शब्द बदलून पहा.',
  'products_count': '@count उत्पादने',

  // Product details
  'product_details': 'उत्पादन तपशील',
  'select_size': 'आकार निवडा',
  'select_color': 'रंग निवडा',
  'in_stock': 'स्टॉकमध्ये आहे',
  'out_of_stock': 'स्टॉकमध्ये नाही',
  'only_left': 'फक्त @count शिल्लक!',
  'description': 'वर्णन',
  'specifications': 'वैशिष्ट्ये',
  'reviews': 'परीक्षणे',
  'ratings_reviews': 'रेटिंग आणि परीक्षणे',
  'related_products': 'संबंधित उत्पादने',
  'similar_products': 'सारखी उत्पादने',
  'add_to_cart': 'कार्टमध्ये टाका',
  'go_to_cart': 'कार्ट पहा',
  'buy_now': 'आता खरेदी करा',
  'estimated_delivery': '@date पर्यंत अंदाजे वितरण',
  'available_offers': 'उपलब्ध ऑफर',
  'share_product_text': 'The Ramp वर @name पहा!',
  'select_size_first': 'कृपया आकार निवडा',
  'select_color_first': 'कृपया रंग निवडा',
  'added_to_cart': 'कार्टमध्ये टाकले',
  'added_to_wishlist': 'विशलिस्टमध्ये जोडले',
  'removed_from_wishlist': 'विशलिस्टमधून काढले',

  // Wishlist
  'wishlist_title': 'माझी विशलिस्ट',
  'wishlist_empty': 'तुमची विशलिस्ट रिकामी आहे',
  'wishlist_empty_desc': 'कोणत्याही उत्पादनावरील हार्ट दाबून ते इथे जतन करा.',
  'move_to_cart': 'कार्टमध्ये हलवा',

  // Cart
  'cart_title': 'माझे कार्ट',
  'cart_empty': 'तुमचे कार्ट रिकामे आहे',
  'cart_empty_desc': 'उत्पादने पहा आणि कार्टमध्ये टाका.',
  'start_shopping': 'खरेदी सुरू करा',
  'save_for_later': 'नंतरसाठी जतन करा',
  'saved_for_later': 'नंतरसाठी जतन केलेले',
  'move_back_to_cart': 'कार्टमध्ये हलवा',
  'remove': 'काढा',
  'coupon_code': 'कूपन कोड',
  'apply_coupon': 'लागू करा',
  'coupon_applied': 'कूपन लागू झाले!',
  'coupon_invalid': 'अवैध किंवा कालबाह्य कूपन',
  'coupon_min_order': 'या कूपनसाठी किमान ऑर्डर @amount आहे',
  'price_details': 'किंमत तपशील',
  'subtotal': 'उप-एकूण',
  'discount': 'सूट',
  'coupon_discount': 'कूपन सूट',
  'delivery_charges': 'वितरण शुल्क',
  'taxes': 'कर',
  'total_amount': 'एकूण रक्कम',
  'free_shipping_msg': 'मोफत वितरणासाठी @amount अधिक जोडा',
  'proceed_to_checkout': 'चेकआउट करा',
  'quantity': 'नग',

  // Checkout
  'checkout_title': 'चेकआउट',
  'delivery_address': 'वितरण पत्ता',
  'add_address': 'पत्ता जोडा',
  'add_new_address': 'नवीन पत्ता जोडा',
  'edit_address': 'पत्ता बदला',
  'delete_address_confirm': 'हा पत्ता हटवायचा?',
  'no_addresses': 'जतन केलेले पत्ते नाहीत',
  'no_addresses_desc': 'पुढे जाण्यासाठी वितरण पत्ता जोडा.',
  'full_name': 'पूर्ण नाव',
  'address_line1': 'घर क्र., इमारत, रस्ता',
  'address_line2': 'परिसर, भाग (ऐच्छिक)',
  'city': 'शहर',
  'state': 'राज्य',
  'pincode': 'पिन कोड',
  'address_type': 'पत्त्याचा प्रकार',
  'address_home': 'घर',
  'address_work': 'कार्यालय',
  'address_other': 'इतर',
  'default_address': 'डीफॉल्ट पत्ता',
  'delivery_options': 'वितरण पर्याय',
  'delivery_standard': 'मानक वितरण',
  'delivery_standard_desc': '3–7 कामकाजाचे दिवस',
  'delivery_express': 'एक्सप्रेस वितरण',
  'delivery_express_desc': '1–2 कामकाजाचे दिवस (+₹99)',
  'payment_method': 'पेमेंट पद्धत',
  'pay_razorpay': 'कार्ड / नेटबँकिंग / वॉलेट',
  'pay_upi': 'UPI',
  'pay_cod': 'कॅश ऑन डिलिव्हरी',
  'order_review': 'ऑर्डर पुनरावलोकन',
  'place_order': 'ऑर्डर करा',
  'pay_now': '@amount भरा',
  'order_success': 'ऑर्डर यशस्वीरित्या झाली!',
  'order_success_desc': 'खरेदीसाठी धन्यवाद. माझ्या ऑर्डरमध्ये ट्रॅक करा.',
  'view_order': 'ऑर्डर पहा',
  'payment_failed_title': 'पेमेंट अयशस्वी',
  'payment_failed_desc': 'तुमचे पेमेंट प्रक्रिया होऊ शकले नाही. पैसे कापले गेले नाहीत, किंवा परत केले जातील.',
  'retry_payment': 'पेमेंट पुन्हा करा',
  'payment_cancelled': 'पेमेंट रद्द केले',

  // Orders
  'my_orders': 'माझ्या ऑर्डर',
  'orders_empty': 'अजून ऑर्डर नाहीत',
  'orders_empty_desc': 'खरेदीनंतर तुमच्या ऑर्डर इथे दिसतील.',
  'order_id': 'ऑर्डर आयडी',
  'order_status_pending': 'प्रलंबित',
  'order_status_confirmed': 'पुष्टी झाली',
  'order_status_shipped': 'पाठवले',
  'order_status_out_for_delivery': 'वितरणासाठी निघाले',
  'order_status_delivered': 'वितरित झाले',
  'order_status_cancelled': 'रद्द केले',
  'order_status_returned': 'परत केले',
  'order_status_return_requested': 'परतीची विनंती',
  'tab_current': 'चालू',
  'tab_completed': 'पूर्ण',
  'tab_cancelled': 'रद्द',
  'tab_returned': 'परत',
  'order_details': 'ऑर्डर तपशील',
  'order_tracking': 'ऑर्डर ट्रॅकिंग',
  'cancel_order': 'ऑर्डर रद्द करा',
  'cancel_order_confirm': 'तुम्हाला ही ऑर्डर रद्द करायची आहे का?',
  'order_cancelled_msg': 'ऑर्डर रद्द केली',
  'return_order': 'परतीची विनंती करा',
  'return_reason': 'परतीचे कारण',
  'return_requested_msg': 'परतीची विनंती केली',
  'invoice': 'बीजक',
  'reorder': 'पुन्हा ऑर्डर करा',
  'items_count': '@count वस्तू',
  'ordered_on': '@date रोजी ऑर्डर केली',
  'paid_via': '@method द्वारे पेमेंट',
  'shipping_address': 'शिपिंग पत्ता',

  // Profile
  'profile_title': 'माझे प्रोफाइल',
  'edit_profile': 'प्रोफाइल बदला',
  'display_name': 'नाव',
  'email': 'ईमेल (ऐच्छिक)',
  'profile_updated': 'प्रोफाइल अपडेट झाले',
  'saved_addresses': 'जतन केलेले पत्ते',
  'saved_payments': 'जतन केलेल्या पेमेंट पद्धती',
  'notifications_title': 'सूचना',
  'notifications_empty': 'अजून सूचना नाहीत',
  'language': 'भाषा',
  'select_language': 'भाषा निवडा',
  'theme': 'थीम',
  'theme_system': 'सिस्टम डीफॉल्ट',
  'theme_light': 'लाइट',
  'theme_dark': 'डार्क',
  'guest': 'पाहुणे',

  // Search
  'search_title': 'शोधा',
  'recent_searches': 'अलीकडील शोध',
  'trending_searches': 'ट्रेंडिंग शोध',
  'no_results_for': '"@query" साठी कोणतेही निकाल नाहीत',
  'voice_search_coming_soon': 'व्हॉइस शोध लवकरच येत आहे',

  // Reviews
  'write_review': 'परीक्षण लिहा',
  'your_rating': 'तुमचे रेटिंग',
  'review_hint': 'या उत्पादनाचा तुमचा अनुभव सांगा…',
  'add_photos': 'फोटो जोडा',
  'submit_review': 'परीक्षण सबमिट करा',
  'review_submitted': 'धन्यवाद! तुमचे परीक्षण सबमिट झाले.',
  'helpful': 'उपयुक्त',
  'no_reviews': 'अजून परीक्षणे नाहीत. पहिले परीक्षण तुम्ही लिहा!',
  'based_on_reviews': '@count परीक्षणांवर आधारित',
  'login_to_review': 'परीक्षण लिहिण्यासाठी लॉग इन करा',

  // Admin panel
  'admin_panel': 'अ‍ॅडमिन पॅनेल',
  'admin_products': 'उत्पादने',
  'admin_categories': 'श्रेणी',
  'admin_banners': 'बॅनर',
  'admin_coupons': 'कूपन',
  'add_product': 'उत्पादन जोडा',
  'edit_product': 'उत्पादन बदला',
  'add_category': 'श्रेणी जोडा',
  'edit_category': 'श्रेणी बदला',
  'add_subcategory': 'उपश्रेणी जोडा',
  'add_banner': 'बॅनर जोडा',
  'edit_banner': 'बॅनर बदला',
  'add_coupon': 'कूपन जोडा',
  'edit_coupon': 'कूपन बदला',
  'field_name': 'नाव',
  'field_brand': 'ब्रँड',
  'field_category': 'श्रेणी',
  'field_subcategory': 'उपश्रेणी (ऐच्छिक)',
  'field_mrp': 'MRP (₹)',
  'field_price': 'विक्री किंमत (₹)',
  'field_stock': 'स्टॉक संख्या',
  'field_colors': 'रंग (स्वल्पविरामाने वेगळे)',
  'field_sizes': 'आकार (स्वल्पविरामाने वेगळे)',
  'field_images': 'प्रतिमा URL (प्रति ओळ एक)',
  'field_keywords': 'शोध कीवर्ड (स्वल्पविरामाने वेगळे)',
  'field_description': 'वर्णन',
  'field_specs': 'वैशिष्ट्ये (प्रति ओळ key: value)',
  'field_offers': 'ऑफर (प्रति ओळ एक)',
  'field_sort_order': 'क्रम क्रमांक',
  'field_image_url': 'प्रतिमा URL',
  'field_title': 'शीर्षक',
  'field_active': 'सक्रिय',
  'flag_featured': 'फीचर्ड (शिफारस केलेले)',
  'flag_bestseller': 'बेस्ट सेलर',
  'flag_flash_sale': 'फ्लॅश सेल',
  'flash_sale_hours': 'फ्लॅश सेल कालावधी (आतापासून तास)',
  'field_target': 'टॅप लक्ष्य',
  'target_none': 'काहीही नाही',
  'target_category': 'श्रेणी',
  'target_product': 'उत्पादन',
  'field_target_id': 'लक्ष्य ID (श्रेणी/उत्पादन)',
  'field_coupon_code': 'कूपन कोड',
  'field_coupon_type': 'प्रकार',
  'coupon_percent': 'टक्के सूट',
  'coupon_flat': 'सरळ रक्कम सूट',
  'field_coupon_value': 'मूल्य (% किंवा ₹)',
  'field_min_order': 'किमान ऑर्डर (₹)',
  'field_max_discount': 'कमाल सूट (₹, 0 = नाही)',
  'field_expiry_days': 'कालबाह्य (दिवस, 0 = कधीही नाही)',
  'saved_success': 'जतन केले',
  'deleted_success': 'हटवले',
  'delete_confirm_generic': 'ही वस्तू हटवायची? हे पूर्ववत करता येणार नाही.',
  'no_items_yet': 'इथे अजून काही नाही. जोडण्यासाठी + दाबा.',
  'admin_subtitle': 'स्टोअर सामग्री व्यवस्थापित करा',
};
